---
apiVersion: runtimes.management.ibm.com/v1
kind: Runtime
metadata:
  name: mqruntime-mq
  namespace: default
spec:
  description: MQ Offers..... Description
  displayName: IBM MQ
  search:
    cluster-based:
      kind: statefulset
      label: "app=ibm-mq"
    vm-based:
      label: "app.management.ibm.com/ibm-mq=true"
  dynamicdetail:
    vm-based:
      columns:
        - displayName: Overview
          source: applicationmgmt
          columnItems:
            - displayName: Channel Initiator Status
              target: channelInitiatorStatus
            - displayName: Command Server Status
              target: commandServerStatus
            - displayName: Manager Status
              target: managerStatus
        - displayName: Connections
          source: metric
          columnItems:
            - displayName: Total Connections
              target: connectionCount
            - displayName: Server Connections
              target: serverConnections
        - displayName: Queues
          source: metric
          columnItems:
            - displayName: Queues with high depth
              target: highDepthQueueCount
            - displayName: Dead letter queue depth
              target: dlqDepth
            - displayName: Open Queues
              target: openQueueCount
            - displayName: Total Messages
              target: totalMessages
        - displayName: Channels
          source: metric
          columnItems:
            - displayName: Channel Connections Not Running
              target: currentChannelConnectionsNotRunning
            - displayName: In doubt channel connections
              target: inDoubtChannelConnections
            - displayName: Percent Maximum Channels
              target: percentMaximumChannels
      applicationmgmt:
        join:
          host: hostName
          name: managerName
        resourceType: mqManager
    cluster-based:
      applicationmgmt:
        join:
          cluster: clusterName
          name: ibmmq_service_name
          namespace: ibmmq_service_namespace
        resourceType: ibmmq_qm
      columns:
      - displayName: Overview
        columnItems:
          - displayName: Queue Manager Name
            target: ibmmq_qmgr_name
          - displayName: Queue Manager Status
            target: ibmmq_qmgr_status
        source: applicationmgmt
      - displayName: Activity
        columnItems:
          - displayName: Total Connections
            target: ibmmq_qmgr-ibmmq_qmgr_mqconn_mqconnx_total
          - displayName: Total GET (non-persistent)
            target: ibmmq_qmgr-ibmmq_qmgr_non_persistent_message_destructive_get_total
          - displayName: Total GET (persistent)
            target: ibmmq_qmgr-ibmmq_qmgr_persistent_message_destructive_get_total
          - displayName: Total PUT/PUT1 (non-persistent)
            target: ibmmq_qmgr-ibmmq_qmgr_non_persistent_message_put_put1_total
          - displayName: Total PUT/PUT1 (persistent)
            target: ibmmq_qmgr-ibmmq_qmgr_persistent_message_put_put1_total
        source: metric
      - displayName: Performance
        columnItems:
          - displayName: File System Free Percent
            target: ibmmq_qmgr-ibmmq_qmgr_queue_manager_file_system_free_space_percentage
          - displayName: RAM Free Percent
            target: ibmmq_qmgr-ibmmq_qmgr_ram_free_percentage
          - displayName: System CPU
            target: ibmmq_qmgr-ibmmq_qmgr_system_cpu_time_estimate_for_queue_manager_percentage
          - displayName: User CPU
            target: ibmmq_qmgr-ibmmq_qmgr_user_cpu_time_estimate_for_queue_manager_percentage
        source: metric
